# The URL the site will be built for
base_url = "https://shantou.University"

# page title
title = "ST.U・ShanTou.Unversity"
description = "ST.U（ShanTou.University）是汕头大学非官方校友平台，提供校友联络、校园资讯、返校指南、学业指南等一站式服务，致力于连接每一位汕大人，打造有温度的校友社区。"
author = "ST.U"

# theme
theme = "tabi"
# git submodule add https://github.com/welpo/tabi.git themes/tabi
# git submodule update --remote themes/tabi

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
# build_search_index = false

# language
default_language = "zh-Hans"
generate_feeds = true

taxonomies = [{name = "tags", feed = true}]

[languages.en]
title = "ST.U・ShanTou.Unversity"
generate_feeds = true
taxonomies = [{name = "tags", feed = true}]
# build_search_index = true

[markdown.highlighting]
style = "class"
theme = "ayu-dark"

[extra]
favicon = "logo.webp"

# Put all your custom variables here
socials = [
    { name = "github", url = "https://github.com/ShanTouUniversity", icon = "github" }
]

email = "ZGV2QFNoYW5Ub3UuVW5pdmVyc2l0eQ=="

remote_repository_url = "https://github.com/ShanTouUniversity/www"

mermaid = true 
copy_button = true
show_author = true

long_date_format = "%Y/%m/%d"
short_date_format = "%Y/%m/%d"

menu = [
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "archive", url = "archive", trailing_slash = true },
    { name = "tags", url = "tags", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
    { name = "nav_site", url = "https://nav.shantou.university", trailing_slash = true },
    { name = "news_site", url = "https://news.shantou.university", trailing_slash = true },
    { name = "voice_site", url = "https://voice.shantou.university", trailing_slash = true },
    { name = "space_site", url = "https://space.shantou.university", trailing_slash = true },
]