# The URL the site will be built for
base_url = "https://shantou.University"

# page title
title = "ST.U・ShanTou.Unversity"

# theme
theme = "tabi"
# git submodule add https://github.com/welpo/tabi.git themes/tabi
# git submodule update --remote themes/tabi

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
# build_search_index = false

# language
default_language = "zh-Hans"
generate_feeds = true

taxonomies = [{name = "tags", feed = true}]

[languages.en]
title = "ST.U・ShanTou.Unversity"
generate_feeds = true
taxonomies = [{name = "tags", feed = true}]
# build_search_index = true



[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
favicon = "logo.webp"

# Put all your custom variables here
socials = [
    { name = "github", url = "https://github.com/ShanTouUniversity", icon = "github" }
]

email = "ZGV2QFNoYW5Ub3UuVW5pdmVyc2l0eQ=="

remote_repository_url = "https://github.com/ShanTouUniversity/www"

mermaid = true 
copy_button = true